version: '3'

services:
  app:
    container_name: ecs-demo-php-simple-app

    # build: . -> uses Dockerfile in current folder as docker-compose.yml to build the container
    build: .
    image: ecs-demo-php-simple-app:latest
#    env_file: .env
    volumes:
#      - ./.docker/apache/default.conf:/tmp/default.template
      - ./src:/var/www/html
    ports:
      - "80:80"
    restart: "no"
    #network_mode: host
    #entrypoint: ["/docker-entrypoint.sh"]
