version: '3'

services:
  app:
    container_name: base-php-fpm

    # build: . -> uses Dockerfile in current folder as docker-compose.yml to build the container
    build: .
    image: base-php-fpm:latest
#    env_file: .env
    volumes:
#      - ./.docker/apache/default.conf:/tmp/default.template
      - ./src:/var/www/html
    ports:
      - "80:80"
    restart: "no"
